version: "3"

name: livhtec-site

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
      - ./docker-command.sh:/home/utils/docker-command.sh
  build-frontend:
    build:
      context: .
      dockerfile: build.Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./:/home/app
      - ./build.docker-command.sh:/home/utils/build.docker-command.sh
